version: '3'
services:
    app:
        container_name: apiapplicationcontainer
        build: .
        image: apiapplication:v1
        restart: unless-stopped
        ports:
            - 30001:30001
        expose:
            - 30001
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_DATABASE}
            SPRING_DATASOURCE_USERNAME: '${DB_USERNAME}'
            SPRING_DATASOURCE_PASSWORD: '${DB_PASSWORD}'
            SERVICE_TAGS: prod
            SERICE_NAME: springapi
        depends_on:
            - mysql
        networks:
            - soap
    mysql:
        image: 'mysql/mysql-server:8.0.22'
        ports:
            - '8181:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'soap-mysql:/var/lib/mysql'
        networks:
            - soap
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        networks:
            - soap
        ports:
            - 8001:80
networks:
    soap:
        driver: bridge
volumes:
    soap-mysql:
        driver: local
